### ISSUE TITLE
Button: Sollten alle Kombinationen von Modus und Variante erlaubt sein?

### ISSUE THREAD

**Issue by CGRBZH** [statistikZH/leu#101]
Zur Diskussion: Machen die Varianten secondary und ghost im Modus inverted Sinn (buttons selber sind in einem dunkleren blau auf blauem Hintergrund) oder sollten die nicht eher unterbunden sein?

Beispiel inverted und secondary:

![Image](https://github.com/statistikZH/leu/assets/47334326/ff3d71a1-dd5f-4dd5-968c-d0b696826818)

Beispiel inverted und ghost:

![Image](https://github.com/statistikZH/leu/assets/47334326/df6974cf-ef78-4e73-bbc2-c6449c633d9e)

**Comment by daenub** [comment]
Nein das macht schon SInn.
Die sind so umgesetzt wie sie im Design System definiert sind:

https://www.figma.com/file/d6Pv21UVUbnBs3AdcZijHmbN/KTZH-Design-System?type=design&node-id=0-1&mode=design&t=hqZBsyru4dQToIBz-11
