### ISSUE TITLE
Dialog

### ISSUE THREAD

**Issue by cubmic** [statistikZH/leu#228]
Siehe Figma:
https://www.figma.com/design/d6Pv21UVUbnBs3AdcZijHmbN/KTZH-Design-System?node-id=18180-165796&t=QIK67oQCWpdWnvFR-11

https://www.figma.com/design/d6Pv21UVUbnBs3AdcZijHmbN/KTZH-Design-System?node-id=16052-88818&t=QIK67oQCWpdWnvFR-11

**Comment by daenub** [comment]
Notizen / Was gerade aufgefallen ist:
 
- Buttons brechen auf kleinem Screen um ragen über Dialog hinaus
- Brauchts die Grid Klassen? Laut Figma brauchts glaube ich kein Grid.
- Modal schliessen wenn man auf den Backdrop klickt?
- Schliessen Label ist nicht sauber ausgerichtet.
- Typography Variablen verwenden.
