### ISSUE TITLE
Range Slider

### ISSUE THREAD

**Issue by daenub** [statistikZH/leu#7]
Kommentar von Res im Confluence:
> wir müssen eventuell zuerst noch besprechen, ob das mit accessability überhaupt sinnvoll ist. Ich habe im Moment auch Slider mit Play-Button in Betrieb.

**Comment by resmartiZH** [comment]
Plazierung der Thumb Value Labels beim zweiseitigen Slider muss ich noch bereinigen. Sollte zentriert sein, wenn sie sich nicht zu nahe kommen.

**Comment by resmartiZH** [comment]
> Case mit mehrereen Thumbs:
> 
>     * Beide bewegbar
ist erledigt
> 
>     * nur einer bewegbar, anderer Fix
muss ich noch umsetzen

**Comment by resmartiZH** [comment]
> Handling von Timestamps?

@daenub was für ein timestamp hättest du gerne?

**Comment by daenub** [comment]
@resmartiZH 

Ich hatte die Bemerkung mit dem Timestamp mal quasi als Reminder gepostet, dass wir bei der Umsetzung sicher noch dran denken.

Ich frage mich ob es vielleicht mehr Sinn macht, einen generischen Einstiegspunkt zu gewähren um den Wert zu formatieren.
Also z.B. ein Property `outputFormatter`, welches eine Funktion entgegennimmt.

Shoelace macht das ähnlich:
https://shoelace.style/components/range#custom-tooltip-formatter

Somit kann man je nach Anwendungsfall selbst steuern wie der Output dargestellt wird.
