### ISSUE TITLE
Dropdown: Wie wird divided gesetzt?

### ISSUE THREAD

**Issue by CGRBZH** [statistikZH/leu#99]
Wie ist vorgesehen, dass die divided Optionen gesetzt werden?

Die Lösung über Item Attribute _divided_, welches mit gibt ob eine Trennlinie angezeigt wird oder nicht, finde ich aus Anwendersicht schöner. Siehe Beispiel [hier](https://element-plus.org/en-US/component/dropdown.html#menu-hiding-behavior).

`<el-dropdown-item divided>Action 4</el-dropdown-item>`

Besser als [diese Lösung](https://shoelace.style/components/dropdown).

**Comment by daenub** [comment]
Momentan wird der Divider mit einem `<hr>` Element gesetzt.

Warum findest du den Ansatz mit dem `divided` attribute schöner?

Der Divider gehört für mich nicht zum Item dazu, sondern trennt das Item von anderen ab. Darum habe ich das als separates Element angewendet.

**Comment by daenub** [comment]
Beim nativen `<select>` Element wird auch `<hr>` als divider verwendet.
Deshalb schliesse ich dieses Issue nun. Kann aber gerne wieder geöffnet werden, falls es noch Anmerkungen gibt.
